begin;

create extension if not exists pgcrypto;

create table if not exists public.areas (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  parent_id uuid references public.areas(id) on delete set null,
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  description text,
  level integer not null default 100,
  system_role boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.permissions (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  module text not null,
  action text not null,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(module, action)
);

create table if not exists public.role_permissions (
  role_id uuid not null references public.roles(id) on delete cascade,
  permission_id uuid not null references public.permissions(id) on delete cascade,
  granted boolean not null default true,
  created_at timestamptz not null default now(),
  primary key(role_id, permission_id)
);

create table if not exists public.employees (
  id uuid primary key default gen_random_uuid(),
  employee_number text unique,
  first_name text not null,
  last_name text not null,
  corporate_email text not null unique,
  personal_email text,
  phone text,
  extension text,
  position text,
  area_id uuid references public.areas(id) on delete set null,
  manager_id uuid references public.employees(id) on delete set null,
  hire_date date,
  termination_date date,
  status text not null default 'active' check (status in ('active','inactive','leave','terminated')),
  photo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint employees_corporate_email_domain check (lower(corporate_email) like '%@mcydj.mx')
);

alter table public.profiles add column if not exists employee_id uuid references public.employees(id) on delete set null;
alter table public.profiles add column if not exists role_id uuid references public.roles(id) on delete set null;
alter table public.profiles add column if not exists area_id uuid references public.areas(id) on delete set null;
alter table public.profiles add column if not exists personal_email text;
alter table public.profiles add column if not exists last_login_at timestamptz;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create unique index if not exists uq_profiles_employee_id on public.profiles(employee_id) where employee_id is not null;
create index if not exists idx_profiles_role_id on public.profiles(role_id);
create index if not exists idx_profiles_area_id on public.profiles(area_id);
create index if not exists idx_employees_area_id on public.employees(area_id);
create index if not exists idx_employees_manager_id on public.employees(manager_id);
create index if not exists idx_employees_status on public.employees(status);
create index if not exists idx_role_permissions_role on public.role_permissions(role_id);
create index if not exists idx_role_permissions_permission on public.role_permissions(permission_id);

create table if not exists public.user_permissions (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  permission_id uuid not null references public.permissions(id) on delete cascade,
  granted boolean not null,
  reason text,
  granted_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(profile_id, permission_id)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  actor_email text,
  action text not null,
  entity_type text not null,
  entity_id text,
  summary text,
  old_data jsonb,
  new_data jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_actor on public.audit_logs(actor_profile_id);
create index if not exists idx_audit_logs_entity on public.audit_logs(entity_type, entity_id);
create index if not exists idx_audit_logs_created_at on public.audit_logs(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_areas_updated_at on public.areas;
create trigger trg_areas_updated_at before update on public.areas for each row execute function public.set_updated_at();
drop trigger if exists trg_roles_updated_at on public.roles;
create trigger trg_roles_updated_at before update on public.roles for each row execute function public.set_updated_at();
drop trigger if exists trg_employees_updated_at on public.employees;
create trigger trg_employees_updated_at before update on public.employees for each row execute function public.set_updated_at();
drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists trg_user_permissions_updated_at on public.user_permissions;
create trigger trg_user_permissions_updated_at before update on public.user_permissions for each row execute function public.set_updated_at();

insert into public.areas(code,name,sort_order) values
('direccion-general','Dirección General',10),
('contabilidad','Contabilidad',20),
('fiscal','Fiscal',30),
('auditoria','Auditoría',40),
('finanzas','Finanzas',50),
('evaluacion-proyectos','Evaluación de Proyectos',60),
('administracion','Administración',70),
('recursos-humanos','Recursos Humanos',80),
('sistemas','Sistemas',90),
('comercial','Comercial',100)
on conflict(code) do update set name=excluded.name, active=true;

insert into public.roles(code,name,description,level,system_role) values
('director','Director General','Acceso total al sistema',10,true),
('socio','Socio','Acceso directivo amplio',20,true),
('gerente','Gerente','Gestión de área y equipo',30,true),
('coordinador','Coordinador','Coordinación operativa',40,true),
('consultor_senior','Consultor Senior','Operación especializada',50,true),
('consultor','Consultor','Operación estándar',60,true),
('auxiliar','Auxiliar','Operación limitada',70,true),
('recepcion','Recepción','Agenda y atención inicial',80,true),
('sistemas','Sistemas','Administración técnica',15,true),
('invitado','Invitado','Solo lectura autorizada',100,true)
on conflict(code) do update set name=excluded.name, description=excluded.description, level=excluded.level, active=true;

insert into public.permissions(code,module,action,description) values
('users.read','users','read','Consultar usuarios'),
('users.create','users','create','Crear usuarios'),
('users.update','users','update','Editar usuarios'),
('users.disable','users','disable','Activar o desactivar usuarios'),
('users.reset_password','users','reset_password','Restablecer contraseñas'),
('roles.read','roles','read','Consultar roles'),
('roles.manage','roles','manage','Administrar roles y permisos'),
('areas.read','areas','read','Consultar áreas'),
('areas.manage','areas','manage','Administrar áreas'),
('audit.read','audit','read','Consultar bitácora'),
('agenda.read','agenda','read','Consultar Agenda NOMIPAQ'),
('agenda.create','agenda','create','Crear reservas'),
('agenda.update','agenda','update','Reagendar reservas'),
('agenda.cancel','agenda','cancel','Cancelar reservas'),
('tools.read','tools','read','Consultar herramientas'),
('tools.execute','tools','execute','Ejecutar herramientas'),
('clients.read','clients','read','Consultar clientes'),
('clients.create','clients','create','Crear clientes'),
('clients.update','clients','update','Editar clientes'),
('clients.delete','clients','delete','Eliminar clientes'),
('projects.read','projects','read','Consultar proyectos'),
('projects.create','projects','create','Crear proyectos'),
('projects.update','projects','update','Editar proyectos')
on conflict(code) do update set description=excluded.description, active=true;

insert into public.role_permissions(role_id, permission_id, granted)
select r.id, p.id, true
from public.roles r cross join public.permissions p
where r.code in ('director','sistemas')
on conflict(role_id,permission_id) do update set granted=true;

insert into public.role_permissions(role_id, permission_id, granted)
select r.id, p.id, true
from public.roles r join public.permissions p on p.code in ('agenda.read','agenda.create','agenda.update','agenda.cancel','tools.read','tools.execute','areas.read')
where r.code in ('socio','gerente','coordinador','consultor_senior','consultor','auxiliar','recepcion')
on conflict(role_id,permission_id) do update set granted=true;

insert into public.role_permissions(role_id, permission_id, granted)
select r.id, p.id, true
from public.roles r join public.permissions p on p.code in ('users.read','areas.read','roles.read','audit.read','clients.read','clients.create','clients.update','projects.read','projects.create','projects.update')
where r.code in ('socio','gerente')
on conflict(role_id,permission_id) do update set granted=true;

update public.profiles p
set role_id = r.id
from public.roles r
where p.role_id is null and lower(coalesce(p.rol,'')) = r.code;

create or replace function public.current_profile_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id from public.profiles where id = auth.uid() or lower(email) = lower(coalesce(auth.jwt()->>'email','')) limit 1;
$$;

create or replace function public.has_permission(permission_code text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select p.id, p.role_id from public.profiles p where p.id = public.current_profile_id() and coalesce(p.activo,true)=true
  ), override_value as (
    select up.granted from public.user_permissions up join me on me.id=up.profile_id join public.permissions pe on pe.id=up.permission_id where pe.code=permission_code
  ), role_value as (
    select rp.granted from public.role_permissions rp join me on me.role_id=rp.role_id join public.permissions pe on pe.id=rp.permission_id where pe.code=permission_code
  )
  select coalesce((select granted from override_value limit 1),(select granted from role_value limit 1),false);
$$;

alter table public.areas enable row level security;
alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.employees enable row level security;
alter table public.profiles enable row level security;
alter table public.user_permissions enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists areas_read on public.areas;
create policy areas_read on public.areas for select to authenticated using (active=true or public.has_permission('areas.manage'));
drop policy if exists areas_manage on public.areas;
create policy areas_manage on public.areas for all to authenticated using (public.has_permission('areas.manage')) with check (public.has_permission('areas.manage'));

drop policy if exists roles_read on public.roles;
create policy roles_read on public.roles for select to authenticated using (active=true or public.has_permission('roles.manage'));
drop policy if exists roles_manage on public.roles;
create policy roles_manage on public.roles for all to authenticated using (public.has_permission('roles.manage')) with check (public.has_permission('roles.manage'));

drop policy if exists permissions_read on public.permissions;
create policy permissions_read on public.permissions for select to authenticated using (public.has_permission('roles.read') or public.has_permission('roles.manage'));
drop policy if exists permissions_manage on public.permissions;
create policy permissions_manage on public.permissions for all to authenticated using (public.has_permission('roles.manage')) with check (public.has_permission('roles.manage'));

drop policy if exists role_permissions_read on public.role_permissions;
create policy role_permissions_read on public.role_permissions for select to authenticated using (public.has_permission('roles.read') or public.has_permission('roles.manage'));
drop policy if exists role_permissions_manage on public.role_permissions;
create policy role_permissions_manage on public.role_permissions for all to authenticated using (public.has_permission('roles.manage')) with check (public.has_permission('roles.manage'));

drop policy if exists employees_read on public.employees;
create policy employees_read on public.employees for select to authenticated using (public.has_permission('users.read') or id=(select employee_id from public.profiles where id=public.current_profile_id()));
drop policy if exists employees_manage on public.employees;
create policy employees_manage on public.employees for all to authenticated using (public.has_permission('users.update')) with check (public.has_permission('users.update'));

drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select to authenticated using (id=public.current_profile_id() or public.has_permission('users.read'));
drop policy if exists profiles_admin_insert on public.profiles;
create policy profiles_admin_insert on public.profiles for insert to authenticated with check (public.has_permission('users.create'));
drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles for update to authenticated using (id=public.current_profile_id() or public.has_permission('users.update')) with check (id=public.current_profile_id() or public.has_permission('users.update'));

drop policy if exists user_permissions_read on public.user_permissions;
create policy user_permissions_read on public.user_permissions for select to authenticated using (profile_id=public.current_profile_id() or public.has_permission('roles.manage'));
drop policy if exists user_permissions_manage on public.user_permissions;
create policy user_permissions_manage on public.user_permissions for all to authenticated using (public.has_permission('roles.manage')) with check (public.has_permission('roles.manage'));

drop policy if exists audit_logs_read on public.audit_logs;
create policy audit_logs_read on public.audit_logs for select to authenticated using (public.has_permission('audit.read'));
drop policy if exists audit_logs_insert on public.audit_logs;
create policy audit_logs_insert on public.audit_logs for insert to authenticated with check (actor_profile_id=public.current_profile_id() or actor_profile_id is null);

commit;
